//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutBotDataBaseWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etiquetas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Etiquetas()
        {
            this.DatosCuriosos = new HashSet<DatosCuriosos>();
            this.Imagenes = new HashSet<Imagenes>();
            this.PreguntasXEtiqueta = new HashSet<PreguntasXEtiqueta>();
        }
    
        public int IdEtiqueta { get; set; }
        public int CodigoEtiqueta { get; set; }
        public string NombreEtiqueta { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string FechaNacimiento { get; set; }
        public string Club { get; set; }
        public string Estatura { get; set; }
        public string Peso { get; set; }
        public string Debut { get; set; }
        public string Pais { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatosCuriosos> DatosCuriosos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagenes> Imagenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreguntasXEtiqueta> PreguntasXEtiqueta { get; set; }
    }
}
