//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutBotDataBaseWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participantes
    {
        public int IdParticipante { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Url { get; set; }
        public Nullable<int> Acumulado { get; set; }
        public string Descripcion { get; set; }
        public string FotoCromo { get; set; }
    }
}
