//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutBotDataBaseWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntasXEtiqueta
    {
        public int IdPreguntaXEtiqueta { get; set; }
        public int IdEtiqueta { get; set; }
        public int IdPregunta { get; set; }
        public string Respuesta { get; set; }
        public Nullable<bool> Bandera { get; set; }
    
        public virtual Etiquetas Etiquetas { get; set; }
        public virtual Preguntas Preguntas { get; set; }
    }
}
