//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutBotDataBaseWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEtiquetasAleatorias
    {
        public int IdEtiqueta { get; set; }
        public int CodigoEtiqueta { get; set; }
        public string NombreEtiqueta { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string FechaNacimiento { get; set; }
        public string Club { get; set; }
        public string Estatura { get; set; }
        public string Peso { get; set; }
        public string Debut { get; set; }
        public string Pais { get; set; }
        public string URLImagen { get; set; }
        public string URLImagenModificada { get; set; }
        public string DatoCurioso { get; set; }
    }
}
